### ISSUE TITLE
run vsd capture without GUI

### ISSUE THREAD

**Issue by RyanChen1997** [clitic/vsd#29]
Firstly, I would like to express my gratitude for developing this tool. It has proven to be extremely useful in capturing m3u8 URLs.

I have successfully executed the tool on my local machine and it functions as expected. However, I have encountered an issue when executing it on Linux.

I connected to my Linux machine via SSH on the terminal and ran the tool. However, when I execute the command `vsd capture ${url}`, it seems to be blocked as shown below:
<img width="652" alt="image" src="https://github.com/clitic/vsd/assets/96852650/9c5b0ed3-c22c-4d4d-bac3-542c18567e52">

I have installed Chrome on the Linux machine, but it lacks a GUI.

Is it possible to use the vsd tool with the sub-command 'capture' in a non-GUI environment?

**Comment by RyanChen1997** [comment]
Update the issue:
After a period of waiting, I received the following error message:
`There are no available ports between 8000 and 9000 for debugging`

**Comment by clitic** [comment]
You can use `--headless` flag to run capture command without gui. Also based on your error it seems like ports between 8000 and 9000 are not available which are required for launching chrome in debug mode.

**Comment by RyanChen1997** [comment]
Thanks for you reply.
The ports between 8000 and 9000 is not used on my machine.
<img width="1166" alt="image" src="https://github.com/clitic/vsd/assets/96852650/336c2da8-61f6-40bc-8f1b-7d3e29c52f2d">
My linux machine information is:
<img width="1127" alt="image" src="https://github.com/clitic/vsd/assets/96852650/9baebcdc-88cd-4a16-ba98-97061877e51a">
My google chrome version:
<img width="600" alt="image" src="https://github.com/clitic/vsd/assets/96852650/c273573f-802c-4526-965f-0585506a5957">

@clitic

**Comment by clitic** [comment]
I have tested from my side. It works completely fine with `--headless` flag. Though it doesn't work without `--headless` flag because gui interface is not available. `capture` was developed my keeping in mind that it would run with gui interface. Running with `--headless` limits its capabilities because most of the websites requires user interactions and then requests playlists.

![download](https://github.com/clitic/vsd/assets/71246790/c84712ca-5bf2-4e41-97c8-c1602259dcad)
![Screenshot 2024-05-23 192852](https://github.com/clitic/vsd/assets/71246790/f30fa320-95b3-4bf4-8488-3e1c6f1dd85a)

**Comment by RyanChen1997** [comment]
Though i have not found the root cause, thanks for you reply.
