### ISSUE TITLE
Open SSL issues on macos ventura (pre-build)

### ISSUE THREAD

**Issue by xvilo** [clitic/vsd#8]
I used the install instructions for MacOS and I'm getting the following result:

```
$ vsd collect "https://example.com/media.m3u8"
dyld[30085]: Library not loaded: /opt/local/libexec/openssl3/lib/libssl.3.dylib
  Referenced from: <74757B88-CD7E-324D-8E72-4B7C313BBCA6> /usr/local/bin/vsd
  Reason: tried: '/opt/local/libexec/openssl3/lib/libssl.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/local/libexec/openssl3/lib/libssl.3.dylib' (no such file), '/opt/local/libexec/openssl3/lib/libssl.3.dylib' (no such file), '/usr/local/lib/libssl.3.dylib' (no such file), '/usr/lib/libssl.3.dylib' (no such file, not in dyld cache)
[1]    30085 abort      vsd collect 
```

Never seen this before, so I'm unsure if you need/want any other info than this. When building from source I get the following:

```
$ RUST_BACKTRACE=1 cargo install vsd                                                                                                                                              
    Updating crates.io index
  Installing vsd v0.2.5
   Compiling libc v0.2.139
   Compiling autocfg v1.1.0
   Compiling proc-macro2 v1.0.50
   Compiling cfg-if v1.0.0
   Compiling quote v1.0.23
   Compiling unicode-ident v1.0.6
   Compiling syn v1.0.107
   Compiling memchr v2.5.0
   Compiling version_check v0.9.4
   Compiling log v0.4.17
   Compiling cc v1.0.78
   Compiling bitflags v1.3.2
   Compiling serde_derive v1.0.152
[.... ]
   Compiling derive_builder v0.12.0
   Compiling auto_generate_cdp v0.4.0
   Compiling requestty v0.5.0
   Compiling headless_chrome v1.0.1
error: failed to run custom build command for `headless_chrome v1.0.1`

Caused by:
  process didn't exit successfully: `/var/folders/0y/42sfx52d50d3g62rxgf9rsxm0000gn/T/cargo-install9bwt9I/release/build/headless_chrome-a638f6c2ef4c7bc0/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /Users/xvilo/.cargo/registry/src/github.com-1ecc6299db9ec823/auto_generate_cdp-0.4.0/src/lib.rs:116:57
  stack backtrace:
     0: _rust_begin_unwind
     1: core::panicking::panic_fmt
     2: core::result::unwrap_failed
     3: core::result::Result<T,E>::unwrap
     4: auto_generate_cdp::init
     5: build_script_build::main
     6: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `vsd v0.2.5`, intermediate artifacts can be found at `/var/folders/0y/42sfx52d50d3g62rxgf9rsxm0000gn/T/cargo-install9bwt9I`
```

**Comment by xvilo** [comment]
Small update, I've deleted the `~/.cargo/` folder as this was suggested on the net, but no luck

**Comment by clitic** [comment]
@xvilo Install openssl library through [macports](https://ports.macports.org/port/openssl) or build it your yourself.

## Building It

### headless_chrome

Building through cargo fails because `rustfmt` is not in path because headless chrome has build.rs script which fails. You can skip to build headless chrome by using `--no-default-features` but `capture` and `collect` commands will be missing.

> process didn't exit successfully: `/var/folders/0y/42sfx52d50d3g62rxgf9rsxm0000gn/T/cargo-install9bwt9I/release/build/headless_chrome-a638f6c2ef4c7bc0/build-script-build` (exit status: 101)

https://github.com/mdrokz/auto_generate_cdp/blob/master/src/lib.rs#L116

### Openssl

Build and install [openssl](https://github.com/openssl/openssl).

Alternative way is to edit openssl dependency inside [Cargo.toml](https://github.com/clitic/vsd/blob/main/Cargo.toml#L28) this will build and link static openssl libs.

```toml
openssl = { version = "0.10", features = ["vendored"] }
```

### Final Step

Install clang or any c/c++ compiler then run.

```bash
CC=clang CXX=clang++ AR=llvm-ar cargo install vsd --release
```

Also, supply `OPENSSL_DIR` variable if you have already  built version of openssl.

**Comment by clitic** [comment]
I think howebrew will work too. It should find openssl v3 dylibs or you should point it by using `DYLD_FALLBACK_LIBRARY_PATH` env variable. You may also need to change dylibs names.

> I don't have a mac. So I was unable to produce a statically linked binary but in future releases I will try to provide atleast linked dylibs.
 
> error: Navigate failed: net::ERR_ABORTED.

This error happens because headless_chrome is unable to open a new tab. This might have failed because by default chrome is launched is `non-headless` mode and chrome is unable to launch a new window. Use `--headless` flag and then try. This will launch chrome in background.

Or simply use chrome devtools.

**Comment by clitic** [comment]
@xvilo I have re-built the macos binary (with static openssl) now you can use it without installing or building openssl.

> error: Navigate failed: net::ERR_ABORTED.

This error can also happen when some webpage elements are not loaded fully. I will try to fix this issue in next release.
